import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";

// API Access Endpoint Token (GraphCMS > Project > Project Settings > API Access > Content API)
const accessEndpoint = "https://api-us-east-1.graphcms.com/v2/cl495aqwz0vh801w8cxos12a7/master";
const graphCMSRequestAPI = new GraphQLClient(accessEndpoint);

// Querying With GraphQL
const graphCMSQuery = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

// Making The API Call/Request (Using "getStaticProps" Function)
export async function getStaticProps() {
  const { posts } = await graphCMSRequestAPI.request(graphCMSQuery);

  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
};

// Homepage Component // Passing "posts" As Props // Passing Down Data In "BlogCard"
export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Blog GraphCMS</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>



        {posts.map(post => (
          <BlogCard
            key={post.id}
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}



      </main>
    </div>
  )
};