import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from "graphql-request"

const accessEndpointAPI = "https://api-us-east-1.graphcms.com/v2/cl495aqwz0vh801w8cxos12a7/master";
const graphcms = new GraphQLClient(accessEndpointAPI);

// const QUERY = gql`
//   {
//     posts {
//       id,
//       title,
//       datePublished,
//       slug,
//       content {
//         html
//       }
//     }
//     author {
//       name,
//       avatar {
//         url
//       }
//     }
//     coverPhoto {
//       publishedAt {
//         createdBy {
//           id
//         }
//         url
//       }
//     }
//   }
// `

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      </main>
    </div>
  )
}
